import { Geist, Geist_Mono, Berkshire_Swash, Bokor } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const bokor = Bokor({
    weight: "400",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${bokor.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
