import { Geist, Geist_Mono, Berkshire_Swash, Bokor } from "next/font/google";
import "./globals.css";

const bokor = Bokor({
    weight: "400",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
            </head>
            <body
                className={`${bokor.variable} ${geistMono.variable} antialiased`}
            >
                {children}
                <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
                <script>
                    AOS.init();
                </script>
            </body>
        </html>
    );
}
